import type { Theme } from "../types";

export const zedcodeDefault: Theme = {
  id: "zedcode-default",
  name: "ZedCode Default",
  description:
    "The signature ZedCode look — deep navy stage with teal and violet glow.",
  editorTheme: { dark: "dracula", light: "github-light" },
  variants: {
    light: {
      colors: {
        background: "#faf8ff",
        foreground: "#1d1b2e",
        card: "#ffffff",
        cardForeground: "#1d1b2e",
        popover: "#ffffff",
        popoverForeground: "#1d1b2e",
        primary: "#0d9488",
        primaryForeground: "#f0fdff",
        secondary: "#efeafd",
        secondaryForeground: "#2a2350",
        muted: "#f1eefb",
        mutedForeground: "#6a6490",
        accent: "#e9e2fb",
        accentForeground: "#2a2350",
        destructive: "#dc2626",
        border: "#e3ddf3",
        input: "#e3ddf3",
        ring: "#14b8a6",
        sidebar: "#f4f0fc",
        sidebarForeground: "#1d1b2e",
        sidebarPrimary: "#7c3aed",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#e9e2fb",
        sidebarAccentForeground: "#2a2350",
        sidebarBorder: "#e3ddf3",
        sidebarRing: "#14b8a6",
      },
    },
    dark: {
      colors: {
        background: "#0f1422",
        foreground: "#e7e9f2",
        card: "#171e33",
        cardForeground: "#e7e9f2",
        popover: "#171e33",
        popoverForeground: "#e7e9f2",
        primary: "#2dd4bf",
        primaryForeground: "#071014",
        secondary: "#232b47",
        secondaryForeground: "#e7e9f2",
        muted: "#222a44",
        mutedForeground: "#9aa3c4",
        accent: "#2a3354",
        accentForeground: "#e7e9f2",
        destructive: "#ff6b6b",
        border: "rgba(154,163,196,0.22)",
        input: "rgba(154,163,196,0.28)",
        ring: "#2dd4bf",
        sidebar: "#0c1120",
        sidebarForeground: "#e7e9f2",
        sidebarPrimary: "#a76bff",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#262f4e",
        sidebarAccentForeground: "#e7e9f2",
        sidebarBorder: "rgba(154,163,196,0.22)",
        sidebarRing: "#2dd4bf",
      },
    },
  },
};

